### PR TITLE
MDP executor debugged and short-term tested with normal and time-critical tasks.

### PR DESCRIPTION
**Pull request by hawesie**
This is is still just responding to add_tasks and set_execution_status services, but should be reasonably robust.

Ready for robot testing.

### CODE REVIEW

**Comment by hawesie** [comment]
@bfalacerda I will continue adding to this PR today, but should be ready for you to use more broadly from tonight onwards.

**Comment by hawesie** [comment]
Ok, good to merge now. This also adds pause and restart execution.

**Comment by bfalacerda** [comment]
@hawesie is there a script that adds tasks around the map so I can leave bob roaming around for testing?

**Comment by hawesie** [comment]
Not explicitly, but anything that previously worked with `add_tasks` should still work. The only constraint is that without logging or scheduling publishing the routines won't work as well. I'll try to get this resolved by the end of tomorrow (hopefully tonight).

**Comment by bfalacerda** [comment]
yeah, Lars did some metric maps yesterday using the add_tasks stuff and it worked fine :)

**Pull request merged**
